### ISSUE TITLE
Nucleus release issue

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Central#32] opened 2016-01-14 10:09 UTC
Hello :-),

We have a big issues with the not-finalized libraries. They are tagged as `0.*`. We require `~0.0` in this case. This is wrong. Here is why.

Try this:
```json
{
    "require": {
        "hoa/ruler": "~1.0"
    }
}
```
and then
```sh
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing hoa/core (2.15.11.09)
    Loading from cache

  - Installing hoa/visitor (1.15.08.17)
    Loading from cache

  - Installing hoa/exception (1.16.01.11)
    Loading from cache

  - Installing hoa/consistency (1.16.01.11)
    Loading from cache

  - Installing hoa/event (1.16.01.11)
    Loading from cache

  - Installing hoa/protocol (1.16.01.11)
    Loading from cache

  - Installing hoa/stream (0.16.01.11)
    Loading from cache

  - Installing hoa/iterator (1.15.10.29)
    Loading from cache

  - Installing hoa/file (0.15.11.09)
    Loading from cache

  - Installing hoa/ustring (3.15.11.09)
    Loading from cache

  - Installing hoa/compiler (2.15.10.29)
    Loading from cache

  - Installing hoa/regex (0.15.08.13)
    Loading from cache

  - Installing hoa/math (0.15.10.26)
    Loading from cache

  - Installing hoa/ruler (1.15.11.09)
    Loading from cache
```
See what's wrong here? Because of `hoa/stream` in `0.…`, it will load `0.16.01.11` and then `hoa/consistency` etc., and it will create a conflict with `hoa/core`.

To solve this, this is easy. Track all `composer.json` files with a `~0.0` dependency, and add this: `~0.0,<=0.15`, it will work. However, I don't want to create another branch just for that, so here is my proposal:
  * Track all `composer.json` with `~0.0` dependencies,
  * Change them to `~0.15.0` or `~0.0,<=0.15`,
  * Commit on `master`,
  * Release a new `0.15.12.31` snapshot,
  * Undo the change in `composer.json` and re-commit,
  * Maybe release a new snapshot, but it's not necessary.

What do you think @hoaproject/hoackers?

**Comment by shulard** [comment] 2016-01-14 10:21
Hello @Hywan!

Is there a way to find quickly all the wrong composer.json repos to update ?

Why rolling back to previous composer version ?

**Comment by Hywan** [comment] 2016-01-14 10:21
No it won't work with this workflow. We need new branches. cc @CircleCode

**Comment by Hywan** [comment] 2016-01-14 10:21
@shulard `ag` is your friend.

**Comment by CircleCode** [comment] 2016-01-14 10:23
I also don't get the point in rolling back the change
what's the point about having new branches?

**Comment by Hywan** [comment] 2016-01-14 10:23
Forget my proposal. How will you fix this situation? Do you understand it?

**Comment by Jir4** [comment] 2016-01-14 10:33
I'm not really aware of what is possible to do with composer but is there a way to have a conditional rules in `composer.json` like `if Hoa\Core > ~3.0` then use `Hoa\SomeLib ~0.16` else `Hoa\SomeLib ~0.15`

**Comment by shulard** [comment] 2016-01-14 10:34
It seems ok now with the new consistency snapshot... I tried to install `ruler: ~1.0` and it works.

**Comment by Hywan** [comment] 2016-01-14 10:41
@shulard No it cannot. This is not related.

**Comment by CircleCode** [comment] 2016-01-14 10:42
To be honest, I think the real problem is that we have stable (tagged) libraries requiring unstable ones.
This mean the assertion "this stable library won't do any BC break" is false since a bc break can occur in any 0.* required library causing the code using the stable library to stop working…

**Comment by CircleCode** [comment] 2016-01-14 10:42
ATM, I don't see any elegant way of solving this.

**Comment by Hywan** [comment] 2016-01-14 10:42
@CircleCode Exactly, and we are working hard on finalizing (making them stable). But we have an issue right now :-). How to solve it?

**Comment by Hywan** [comment] 2016-01-14 10:43
@CircleCode Maybe just throw a notice? With apologies.

**Comment by Jir4** [comment] 2016-01-14 10:44
@Hywan we have ton find a way to flag BC on unstable lib

**Comment by Hywan** [comment] 2016-01-14 10:45
@CircleCode Here is a new proposal. Let's consider `hoa/ruler`. Checkout `1.15.*` (the latest before the BC break), then make the change in the `composer.json` file to only require `~0.0,<0.15` for instance, then commit, release a new snapshot, and here we go. We will have another branch. This is eleguant, isn't it?

**Comment by Hywan** [comment] 2016-01-14 10:45
@Jir4 We should not have unstable libraries in fact.

**Comment by Pierozi** [comment] 2016-01-14 10:45
@Hywan We need tell them to specify the release of all the beta dependencies

**Comment by Pierozi** [comment] 2016-01-14 10:46
until they have drop `Hoa\Core`

**Comment by Jir4** [comment] 2016-01-14 10:47
@Hywan a lib cannot be stable from the beginning, so for each lib that we will able to add, it will have some times where the lib will be unstable

**Comment by CircleCode** [comment] 2016-01-14 10:49
@Pierozi I'm not sure Hoa\Core is THE point: future BC breaks in 0.* libs will do the same.
We have to find a future proof way of handling this.
But your points is interesting: isn't it a way of solving it by letting the user know this point and doing something in its composer file?

@Hywan @Jir4 
> We should not have unstable libraries in fact.

> a lib cannot be stable from the beginning…

I think we MUST NOT (rather than _should not_) have unstable libraries required by stable libraries

**Comment by Jir4** [comment] 2016-01-14 10:51
@CircleCode i agree with your last sentence

**Comment by Jir4** [comment] 2016-01-14 10:54
So 
> @Hywan
Maybe just throw a notice? With apologies.

And expain what to do ? (explain in https://github.com/hoaproject/Central/issues/32#issue-126620651)

**Comment by Pierozi** [comment] 2016-01-14 10:55
@CircleCode you right future BC between dependencies can still exist.

We cannot specify in composer.json a conflit version ?
When trying to load Hoa\Core and Hoa\Stream > 0.16 throw an warning for refuse install

**Comment by CircleCode** [comment] 2016-01-14 10:56
the problem is: is there a way to fix it on the user side?
since the problem occurs on indirect dependencies (requirements from a lub required by the user), i'm not sure its master composer can restrict versions

**Comment by Jir4** [comment] 2016-01-14 10:57
@CircleCode checking git tag ? ^^

**Comment by CircleCode** [comment] 2016-01-14 10:57
if it can be fixed on user side, so we juste have to apologize, explain it, and stabilize any lib required by a stable lib.

Again, how many unstable libraries are concerned? (I mean, how many unstable libs arerequired by stable ones?)

**Comment by Pierozi** [comment] 2016-01-14 10:59
@CircleCode on user side yes, instead let composer install dependencies, specify ourself the last compatible version like i did.

**Comment by CircleCode** [comment] 2016-01-14 11:00
so this seems to be the right and easy way to solve it, isn't it?

**Comment by Jir4** [comment] 2016-01-14 11:02
@CircleCode several ... :s
 I'll check to make a list

**Comment by Pierozi** [comment] 2016-01-14 11:03
Otherwise, each @hoaproject/hoackers take a repo and drop Hoa\Core and then this problems will be solved, and becareful of future BC

**Comment by Jir4** [comment] 2016-01-14 11:04
@Pierozi it will no solve the problem in other project dependencies

**Comment by Hywan** [comment] 2016-01-14 11:26
Please, see https://github.com/hoaproject/Central/issues/32#issuecomment-171609568. This is how to fix it. Thoughts?

**Comment by Hywan** [comment] 2016-01-14 11:26
It's strictly equivalent as maintaining 2 versions of the same software.

**Comment by CircleCode** [comment] 2016-01-14 11:29
@Hywan but if it can be fixed on the user side, it would be better than having to maintain n versions (one for each bc break in unstable libs)

I think we should not follow the multi-versions approach because we don't have enough manpower for this

**Comment by Jir4** [comment] 2016-01-14 11:30
@Hywan it seems the most clean way that we can use but @CircleCode  is right

**Comment by Jir4** [comment] 2016-01-14 11:31
@CircleCode Here the list of unstable lib : 
* https://packagist.org/packages/hoa/devtools 
* https://github.com/hoaproject/Acl
* https://github.com/hoaproject/Dispatcher
* https://github.com/hoaproject/File :heavy_exclamation_mark:
* https://github.com/hoaproject/Graph
* https://github.com/hoaproject/Http :heavy_exclamation_mark:
* https://github.com/hoaproject/Irc
* https://github.com/hoaproject/Mail
* https://github.com/hoaproject/Math :heavy_exclamation_mark:
* https://github.com/hoaproject/Praspel
* https://github.com/hoaproject/Realdom
* https://github.com/hoaproject/Regex
* https://github.com/hoaproject/Socket
* https://github.com/hoaproject/Stream :heavy_exclamation_mark:
* https://github.com/hoaproject/Stringbuffer
* https://github.com/hoaproject/Xml
* https://github.com/hoaproject/Xyl
* https://github.com/hoaproject/Zformat
* https://github.com/hoaproject/Contributions-Atoum-PraspelExtension

I maybe forgot some

**Comment by Hywan** [comment] 2016-01-14 11:47
@CircleCode Yes it can be fixed on the user-side but not easily. We must not ask our users to fix our fails. It's not like maintaining 2 versions of a software, this is just a branch with a small fix living in there, and it solves everything. When `hoa/core` will be removed, we will be able to remove all these branches too.

**Comment by Jir4** [comment] 2016-01-14 11:49
@Hywan so we have to choose a date and announce it as soon as possible

**Comment by Hywan** [comment] 2016-01-14 12:05
@Jir4 Why as soon as possible? We must fix this first. Then it will be calm and safe and we will think about it.

@CircleCode Is it possible with Bhoat to push to another branch than `master`?

**Comment by Jir4** [comment] 2016-01-14 12:07
@Hywan just wanna say we have to announce as soon as the date is choosen

**Comment by CircleCode** [comment] 2016-01-14 12:19
> When hoa/core will be removed, we will be able to remove all these branches too.

@Hywan only until next BC break…

> Here the list of unstable lib…

@Jir4 but which of them is required by any stable lib?

> Is it possible with Bhoat to push to another branch than master?

not now, this is a work that has not been done on Hoa, I think.
IIRC, the push is done with --mirror so all branches are pushed, but only master is listened.
I have to check

**Comment by Jir4** [comment] 2016-01-14 12:27
@CircleCode mainly thoose with an exclamation mark

**Comment by Hywan** [comment] 2016-01-14 12:54
> @CircleCode only until next BC break…

Nop, because we will avoid having unstable dependencies.

So, @hoaproject/hoackers, what do you suggest? We have to take a decision. Maybe we have to make a vote?

**Comment by CircleCode** [comment] 2016-01-14 12:56
> Nop, because we will avoid having unstable dependencies.

what does it mean for stable libs currently depending of unstable libs?

**Comment by Hywan** [comment] 2016-01-14 12:58
@CircleCode We have to stabilize unstable libs and this situation will not happen anymore.

**Comment by camael24** [comment] 2016-01-14 13:00
Make an snapshot with "0.15.0" make sense as an hotfix :D.
And its lets us some time to stabilize unstable libs

**Comment by Hywan** [comment] 2016-01-14 14:13
I have another idea.

We can **delete** the latest tags of **unstable** libraries. Thus, the problem disappears. Then, we create another snapshot but as **stable**. Most libraries are stables now.

Thoughts @hoaproject/hoackers?

**Comment by CircleCode** [comment] 2016-01-14 14:23
I love this idea, but have some remarks:

1. we don't have to do this on libs not required by any stable lib
2. thus, this will imply the following rule: _a lib can pass to a stable status only if all its dependencies are marked as stable_ (I love this rule)
3. we will have to communicate on the tag deletion (this is not a problem, but it has to be done)

**Comment by Jir4** [comment] 2016-01-14 14:29
@Hywan :+1: but we have to be sure that the lib is really stable

@CircleCode :+1: on all your points ( and an other :+1: for the 2, it will avoid further issues )

**Comment by camael24** [comment] 2016-01-14 14:54
@Hywan :+1: 
@CircleCode :+1:

**Comment by shulard** [comment] 2016-01-14 15:14
Hey guys, it seems that you have found the simpler way to handle the current problem :smile:.

For me the 3 points mentioned by @CircleCode are the right rules to be followed.

**Comment by Pierozi** [comment] 2016-01-14 15:23
That mean if i call `Hoa\Ruler` at version `~1.0` the `Hoa\Stream` dependency will be call at `0.*` instead new stable `1.*` ? im not sure

**Comment by Hywan** [comment] 2016-01-14 16:15
@Pierozi Currently, `hoa/ruler` `1.*` and `2.*` require `hoa/stream` `0.*`. What we are going to do is to bump `hoa/stream` to `1.*`, and update `hoa/ruler` `2.*` to use `hoa/stream` `1.*` instead of `0.*`. This way, it will work.

**Comment by Pierozi** [comment] 2016-01-14 16:16
Got it ! :+1:

**Comment by Hywan** [comment] 2016-01-14 16:23
@CircleCode @Jir4 Some unstable libraries are not required at all, like `hoa/irc` or `hoa/math`. Maybe we should keep them at unstable. But `hoa/stream`, `hoa/socket`, `hoa/stringbuffer` or `hoa/file` can be promoted as stable. I will start by these ones. Same for `hoa/regex` etc. Actually, the list is:
```sh
$ cat */composer.json | grep '~0.' | cut -d\  -f 9 | grep hoa | sed -e 's/[": ]*//g' | sort | uniq
hoa/devtools
hoa/dispatcher
hoa/file
hoa/graph
hoa/http
hoa/math
hoa/praspel
hoa/realdom
hoa/regex
hoa/socket
hoa/stream
hoa/stringbuffer
hoa/xml
hoa/xyl
hoa/zformat
```
This is all the libraries we need to update as stables.

Here we go:
* [ ] `hoa/devtools`,
* [ ] `hoa/dispatcher`,
* [ ] `hoa/file`,
* [ ] `hoa/graph`,
* [ ] `hoa/http`,
* [ ] `hoa/math`,
* [ ] `hoa/praspel`,
* [ ] `hoa/realdom`,
* [ ] `hoa/regex`,
* [ ] `hoa/socket`,
* [ ] `hoa/stream`,
* [ ] `hoa/stringbuffer`,
* [ ] `hoa/xml`,
* [ ] `hoa/xyl`,
* [ ] `hoa/zformat`.

It should not take a lot of time.

Reminder of the strategy:
  * Cancel the last snapshot,
  * Create a new snapshot with `devtools:snapshot -b` (`-b` for BC break, it will bump 0 to 1),
  * Update all (needed) libraries to use these new snapshots,
  * Release them.

Agree?

**Comment by Hywan** [comment] 2016-01-14 16:25
Actually the strategy is not that simple. For instance, `hoa/graph` is required by `hoa/acl`, which is unstable. An unstable library can depends of unstable libraries. So we can remove it from the list (applied).

**Comment by Hywan** [comment] 2016-01-14 16:26
Anyway, we can have a better strategy but the final list seems correct. All these libraries are stables. The API didn't change since a long time. Even if it changes, it will be a BC break. It's not a big deal.

Is everyone agree?

**Comment by Hywan** [comment] 2016-01-14 16:27
(just `hoa/http` which is a pure nightmare currently, but I don't care. PSR-7 will be BC break and it will be a good one).

**Comment by Pierozi** [comment] 2016-01-14 16:36
:+1: Agree, about `hoa/zformat` she's the new one, but don't really a problem for me.

**Comment by Metalaka** [comment] 2016-01-14 17:41
@CircleCode, @Hywan Agree, seem good for me

@Pierozi `Hoa\Zformat` is maybe young but it's code isn't ;)

**Comment by Hywan** [comment] 2016-01-14 18:05
@Metalaka Exact about `Hoa\Zformat`.

I am starting. Then lunch, then night and I will finish this night.

**Comment by Hywan** [comment] 2016-01-14 18:12
Note: I don't change the `.State` file.

**Comment by Hywan** [comment] 2016-01-14 20:23
Done. All dependencies, except `hoa/graph`, are not `0.*`.
Next step: Update `composer.json` files to use these new snapshots. I am going to prepare all the commits tonight and create the snapshot tomorrow.

**Comment by Hywan** [comment] 2016-01-14 20:29
To get the list of all libraries to update:
```sh
$ for i in `\ls`; do if test ! -f $i/composer.json; then continue; fi; cd $i; echo $i; cat composer.json | grep 0.~; cd ..; done
```

**Comment by Hywan** [comment] 2016-01-14 21:39
Now, if I install `hoa/ruler` `~1.0`,  I will have:
```sh
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing hoa/core (2.15.11.09)
    Loading from cache

  - Installing hoa/visitor (1.15.08.17)
    Loading from cache

  - Installing hoa/iterator (1.15.10.29)
    Loading from cache

  - Installing hoa/stream (0.15.10.26)
    Loading from cache

  - Installing hoa/file (0.15.11.09)
    Loading from cache

  - Installing hoa/ustring (3.15.11.09)
    Loading from cache

  - Installing hoa/compiler (2.15.10.29)
    Loading from cache

  - Installing hoa/regex (0.15.08.13)
    Loading from cache

  - Installing hoa/math (0.15.10.26)
    Loading from cache

  - Installing hoa/ruler (1.15.11.09)
    Loading from cache
```
which is what we expect!
And now, if I change `~1.0` for `~2.0` and then update, it works great too:
```sh
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing hoa/core (2.15.11.09)
  - Installing hoa/exception (1.16.01.11)
    Loading from cache

  - Installing hoa/consistency (1.16.01.14)
    Loading from cache

  - Installing hoa/event (1.16.01.11)
    Loading from cache

  - Installing hoa/zformat (1.16.01.14)
    Loading from cache

  - Installing hoa/router (3.16.01.14)
    Downloading: 100%

  - Installing hoa/protocol (1.16.01.11)
    Loading from cache

  - Installing hoa/dispatcher (1.16.01.15)
    Downloading: 100%

  - Removing hoa/ustring (3.15.11.09)
  - Installing hoa/ustring (4.16.01.11)
    Loading from cache

  - Removing hoa/stream (0.15.10.26)
  - Installing hoa/stream (1.16.01.14)

  - Removing hoa/iterator (1.15.10.29)
  - Installing hoa/iterator (2.16.01.11)
    Loading from cache

  - Removing hoa/file (0.15.11.09)
  - Installing hoa/file (1.16.01.15)
    Loading from cache

  - Installing hoa/console (3.16.01.14)
    Downloading: 100%

  - Installing hoa/cli (2.16.01.14)
    Downloading: 100%

  - Removing hoa/visitor (1.15.08.17)
  - Installing hoa/visitor (2.16.01.11)
    Loading from cache

  - Removing hoa/compiler (2.15.10.29)
  - Installing hoa/compiler (3.16.01.14)
    Loading from cache

  - Removing hoa/math (0.15.10.26)
  - Installing hoa/math (1.16.01.15)
    Loading from cache

  - Removing hoa/regex (0.15.08.13)
  - Installing hoa/regex (1.16.01.15)
    Loading from cache

  - Removing hoa/ruler (1.15.11.09)
  - Installing hoa/ruler (2.16.01.14)
    Downloading: 100%
```
This is what we expect!

**Comment by Pierozi** [comment] 2016-01-14 21:41
@Hywan Good job !

**Closed** 2016-01-14 21:40 UTC
Labels: bug, difficulty: medium

**Comment by Hywan** [comment] 2016-01-14 21:45
Thank you everyone for your participations! Awesome community :heart:!

**Comment by Jir4** [comment] 2016-01-15 07:55
@Pierozi :+1: 

@Hywan  Thanks for all your work !
